epochs: 300
log_every: 10 
ckpt_every: 50_000
accumulation_steps: 1
lr: 1e-4

results_dir: "./results/pelvis"
# model: "DiM-L/2"
model: "ZigMa-BL/2"
image_size: 224  #[224, 256, 512]
global_batch_size: 1

global_seed: 0
vae: "ema" #choices=["ema", "mse"]
num_workers: 4
ct_ckpt: "./pretrain_ct_encoder/patch_size_2.pt"
dt_rank: 16
d_state: 16

init_from_pretrain_ckpt: False
# pretrain_ckpt_path: "./results/011-DiM-L-2/checkpoints/2180000.pt"  #317 218 312
pretrain_ckpt_path: "results/0200000.pt"  #317 218 312
# init_train_steps: 2_180_000
init_train_steps: 200_000
lr_: 1e-4



#sample
# ckpt: "./results/011-DiM-L-2/checkpoints/2180000.pt"
ckpt: "results/pelvis/067-ZigMa-BL-2/checkpoints/0150000.pt" #"./results/pelvis/019-DiM-B-2/checkpoints/0300000.pt"
save_dir: "./result_sample/pelvis"
seed: 0
sample_global_batch_size: 1 #16
sample_num_steps: 250 #250
sample_num_workers: 1
load_ckpt_type: "ema"   #choices=["ema", "model"]



# train
ct_image_folder_train: '/root/code/CTtoMRI/datasets/SynthRAD2023/train/pelvis/train2D/B_norm/'    #CT
mir_image_folder_train: '/root/code/CTtoMRI/datasets/SynthRAD2023/train/pelvis/train2D/A_norm/'    #MIR
mask_image_folder_train: '/root/code/CTtoMRI/datasets/SynthRAD2023/train/pelvis/train2D/C_norm/'    #mask

# val
ct_image_folder_val: '/root/code/CTtoMRI/datasets/SynthRAD2023/train/pelvis/val2D/B_norm/'    #CT
mir_image_folder_val: '/root/code/CTtoMRI/datasets/SynthRAD2023/train/pelvis/val2D/A_norm/'    #MIR
mask_image_folder_val: '/root/code/CTtoMRI/datasets/SynthRAD2023/train/pelvis/val2D/C_norm/'    #mask